Models/DaneModel.cs
using System.ComponentModel.DataAnnotations;
namespace FormMvc.Models;

public class DaneModel
{
    
    [Required(ErrorMessage = "Proszę podaj Imię")]
    [MinLength(2)]
    public string Imie { get; set; }
    [Required(ErrorMessage = "Proszę podaj nazwisko")]
    [MinLength(2)]
    public string Nazwisko { get; set; }
    [Required(ErrorMessage = "Proszę podaj Email")]
    [RegularExpression(".+\\@.+\\.[a-z]{2,3}")]
    public string Email { get; set; }
    [Required(ErrorMessage = "Proszę podaj hasło")]
    [RegularExpression("^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$")]
    public string Haslo { get; set; }
    public string PotwierdzenieHasla { get; set; }
    [Required(ErrorMessage = "Proszę podaj Nr Telefonu")]
    [Phone]
    public string NumerTelefonu { get; set; }
    public int Wiek { get; set; }
    [Required(ErrorMessage = "Proszę podaj miasto")]
    [MinLength(10), MaxLength(50)]
    public string Miasto { get; set; }
    public enum Miasta { Zgierz, Pabianice, Radzionków, Świecie, Wilkowyje}
    
    public DaneModel()
    {
    }
}

Models/ErrorViewModel.cs
namespace FormMvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DaneController.cs
using FormMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace FormMvc.Controllers;

public class DaneController : Controller
{
    
    [HttpGet]
    public IActionResult Form()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Form(DaneModel daneModel)
    {
        if(ModelState.IsValid)
        {
            if (daneModel.Haslo == daneModel.PotwierdzenieHasla)
            {
                return View("Wynik");
            }
            else
            {
                ModelState.AddModelError("PotwierdzenieHasla", "Hasło i jego potwierdzenie nie są zgodne.");
                return View();
            }
        }
        else
        {
            return View();
        }
    }
    public IActionResult Wynik(DaneModel daneModel)
    {
        return View(daneModel);
    }
    
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FormMvc.Models;

namespace FormMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dane/Form.cshtml
@model DaneModel

@{
    ViewData["Title"] = "Form";
}

@using (Html.BeginForm("Form", "Dane", FormMethod.Post))
{
    @Html.ValidationSummary(false, "", new { @class = "text-danger"})
    <p>Twoje imie: @Html.TextBoxFor(a => a.Imie)</p>
    <p>Twoje nazwisko: @Html.TextBoxFor(a => a.Nazwisko)</p>                                            
    <p>Twoj email: @Html.TextBoxFor(a => a.Email)</p>
    <p>Twoje hasło: @Html.TextBoxFor(a => a.Haslo)</p>  
    <p>Powtórz hasło: @Html.TextBoxFor(a => a.PotwierdzenieHasla)</p>
    <p>Nr telefonu: @Html.TextBoxFor(a => a.NumerTelefonu)</p>
    <p>Twój wiek: @Html.TextBoxFor(a => a.Wiek)</p>
    <p>Twoje miasto: @Html.DropDownListFor(a => a.Miasto, new SelectList(Enum.GetValues(typeof(DaneModel.Miasta))),"wybierz miasto")</p>
                                        
    <input type="submit" value="Zapisz"/>
    <input type="reset" value="Wyczyść"/>
    
    
}

Views/Dane/Wynik.cshtml
@model DaneModel

@{
    ViewData["Title"] = "Wynik";
}

<!DOCTYPE html>

<html>
<head>
    <title>Wynik</title>
    <style>
        .container{
        align-content: center;
        }
        .text-success{
        font-family: "Apple Color Emoji",system-ui;
        font-size: xx-large ;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-success">"Rejestracja zakończona pomyślnie"</h1>
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FormMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FormMvc.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FormMvc</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - FormMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>